spring.application.name=week6assignment

#actuator config
management.endpoints.web.exposure.include=health,info,metrics

# connection with postgresQl
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeDataBase
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true